// <auto-generated />
using System;
using AcousticVision.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcousticVision.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("AcousticVision.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<double>("NoiseCancelation")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("AcousticVision.Models.RoomModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RoomModels", (string)null);
                });

            modelBuilder.Entity("AcousticVision.Models.RoomWall", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WallId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("RoomId", "WallId");

                    b.HasIndex("WallId");

                    b.HasIndex("RoomId", "Position")
                        .IsUnique();

                    b.ToTable("RoomWalls", (string)null);
                });

            modelBuilder.Entity("AcousticVision.Models.SoundReceiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SoundReceivers", (string)null);
                });

            modelBuilder.Entity("AcousticVision.Models.SoundSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Article")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SoundSources", (string)null);
                });

            modelBuilder.Entity("AcousticVision.Models.TestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SourceId");

                    b.HasIndex("RoomId", "SourceId", "ReceiverId")
                        .IsUnique();

                    b.ToTable("TestModels", (string)null);
                });

            modelBuilder.Entity("AcousticVision.Models.Texture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<double>("NoiseCancelation")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Textures", (string)null);
                });

            modelBuilder.Entity("AcousticVision.Models.Wall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TextureId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("TextureId");

                    b.ToTable("Walls", (string)null);
                });

            modelBuilder.Entity("AcousticVision.Models.RoomWall", b =>
                {
                    b.HasOne("AcousticVision.Models.RoomModel", "Room")
                        .WithMany("RoomWalls")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcousticVision.Models.Wall", "Wall")
                        .WithMany("RoomWalls")
                        .HasForeignKey("WallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Wall");
                });

            modelBuilder.Entity("AcousticVision.Models.TestModel", b =>
                {
                    b.HasOne("AcousticVision.Models.SoundReceiver", "Receiver")
                        .WithMany("TestModels")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcousticVision.Models.RoomModel", "Room")
                        .WithMany("TestModels")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcousticVision.Models.SoundSource", "Source")
                        .WithMany("TestModels")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Room");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("AcousticVision.Models.Wall", b =>
                {
                    b.HasOne("AcousticVision.Models.Material", "Material")
                        .WithMany("Walls")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcousticVision.Models.Texture", "Texture")
                        .WithMany("Walls")
                        .HasForeignKey("TextureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Texture");
                });

            modelBuilder.Entity("AcousticVision.Models.Material", b =>
                {
                    b.Navigation("Walls");
                });

            modelBuilder.Entity("AcousticVision.Models.RoomModel", b =>
                {
                    b.Navigation("RoomWalls");

                    b.Navigation("TestModels");
                });

            modelBuilder.Entity("AcousticVision.Models.SoundReceiver", b =>
                {
                    b.Navigation("TestModels");
                });

            modelBuilder.Entity("AcousticVision.Models.SoundSource", b =>
                {
                    b.Navigation("TestModels");
                });

            modelBuilder.Entity("AcousticVision.Models.Texture", b =>
                {
                    b.Navigation("Walls");
                });

            modelBuilder.Entity("AcousticVision.Models.Wall", b =>
                {
                    b.Navigation("RoomWalls");
                });
#pragma warning restore 612, 618
        }
    }
}
